#!/usr/bin/ansible-playbook

#  _   _ ____  __  __     __  ____   _______
# | | | |  _ \|  \/  |    \ \/ /\ \ / /__  /
# | | | | | | | |\/| |_____\  /  \ V /  / /
# | |_| | |_| | |  | |_____/  \   | |  / /_
#  \___/|____/|_|  |_|    /_/\_\  |_| /____|
#

- name: Run the common role against some hosts
  hosts:
    - unifi_udm
  gather_facts: true
  become: yes
  tasks:
    - name: Install the baseline
      include_role:
        name: unifi-netbootxyz
  vars:
    pxe_server: '10.69.5.217' # THIS IS WHAT YOU NEED TO SET TO YOUR NETBOOT.XYZ INSTANCE