- name: Ensure dnsmasq configuration directory exists
  ansible.builtin.file:
    path: /run/dnsmasq.conf.d
    state: directory
    mode: '0755'

- name: Deploy PXE configuration file
  ansible.builtin.template:
    src: "templates/pxe.conf.j2"
    dest: /run/dnsmasq.conf.d/pxe.conf
    owner: root
    group: root
    mode: '0644'
  # vars:
  #   server_ip: "{{ pxe_server_ip }}"  # Use the variable from the playbook.yml file
  notify: restart_dnsmasq

